### ISSUE TITLE
Notificaciones de pago

### ISSUE THREAD

**Issue by JaminsonR** [PagosEnLinea/ESPOL#23]
**Historia de usuario [159610469] Notificar compra**
Como comprador quiero recibir retroalimentación por cada transacción a mi dirección de email para mantenerte notificado acerca de la compra.

**Pull Requests**
- #22 
 
**Fecha de entrega**
16/Enero/2019

**Comment by JaminsonR** [comment]
@alfonsopulido13 esperamos un demo de lo implementado para poder aprobar el PR
cc/ @cmonsalvec @juniverjair

**Comment by juniverjair** [comment]
@JaminsonR  @alfonsopulido13  @cmonsalvec  Se necesitan correciones.
