### ISSUE TITLE
Problemas al correr el sistema

### ISSUE THREAD

**Issue by cmonsalvec** [PagosEnLinea/ESPOL#24]
Tengo problemas al correr el sistema, ¿no será problema relacionado al gitignore?

**Comment by JaminsonR** [comment]
Parece que estas haciendo cambios en otros módulos del proyecto, por favor modificar el PR para poder aprobarlo @juniverjair

**Comment by JaminsonR** [comment]
@cmonsalvec  Por favor confirme que el bug ha sido solucionado
cc/ @juniverjair @alfonsopulido13

**Comment by cmonsalvec** [comment]
Estimados, si se ha solucionado el problema. Muchas gracias. Sin embargo, no veo que se me haya reportado el análisis de impacto. Veo lo han catalogado como crítico, pero me gustaría conocer el porqué. Asegurarse de seguir bien todos los 10 pasos y de tener todas las categorizaciones acordadas.

**Comment by cmonsalvec** [comment]
Gracias, favor continuar para el cierre del ticket tan pronto se hayan cumplido con todos los pasos establecidos en la metodología acordada.

**Comment by JaminsonR** [comment]
Después de revisar que se hayan cumplido con todos los pasos establecidos en la metodología acordada. se procede a cerrar el issue 
cc/ @cmonsalvec @juniverjair @alfonsopulido13
